### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by Daemach** [tarkal/highchart-lambda-export-server#11]
Can I talk you into writing a very quick setup guide for those of us who have never used lambda before?  If you can help me get this working I'll gladly paypal you $$$ for beer or other favorite adult beverage.  Set it up at https://paypal.me

I created a function, uploaded the zip, set the font env variable then tried to test it using the test tab but it returns an error.  How does one access this from an EC2 server?  https://www.screencast.com/t/dY7srlWAu8

**Comment by Daemach** [comment]
$100?

**Comment by tarkal** [comment]
Haha :)
Hi @Daemach... Thats a super kind offer. There is absolutely no need to pay anything. I will gladly share what I know with you for free. I am just very short on time for the next couple of weeks. If you can wait a couple of weeks I will setup a session so we can work out what is going on with your setup. Thx

**Comment by Daemach** [comment]
Well, I'm still willing to pay for help as it's cheaper than beating my head against a wall ;)  Especially if you can do it sooner.  It shouldn't take long.  I've gotten as far as connecting via the API, but when trying to generate a chart using your example object it just times out.  I have it set to 1GB of RAM and 30 second timeout now.  The same object takes 1s on https://export.highcharts.com/

**Comment by Daemach** [comment]
Hmm - I kicked the memory up to 4098 and it completed but took a very long time.  How much memory is recommended?

**Comment by tarkal** [comment]
I am guessing that there is an error in your deployment. I just ran mine and here is the result:

![Screenshot 2021-07-13 at 09 57 06](https://user-images.githubusercontent.com/7042623/125414235-8fb0adf1-ad65-49fd-b26d-4af166c491fa.png)

As you can see. With 640MB it took about 1.5 seconds from cold.

**Comment by Daemach** [comment]
Not sure what could be different...  I'm using the api version of your
code.   Even with 4096 MB configured it takes 6 seconds from cold, 1.6
seconds when warm

**Comment by Daemach** [comment]
![image](https://user-images.githubusercontent.com/12553953/125455324-f95a18cd-0444-428c-97e1-d0ef5c36b3e8.png)

**Comment by Daemach** [comment]
This is the object I'm posting:  

```
{
  "body": {
    "b64": true,
    "options": {
      "chart": {
        "style": {
          "fontFamily": "Monserrat"
        },
        "width": 1024,
        "type": "bar"
      },
      "title": {
        "text": "Historic World Population by Region"
      },
      "subtitle": {
        "text": "Source: Wikipedia.org"
      },
      "xAxis": {
        "categories": [
          "Africa",
          "America",
          "Asia",
          "Europe",
          "Oceania"
        ],
        "title": {
          "text": null
        }
      },
      "yAxis": {
        "min": 0,
        "title": {
          "text": "Population (millions)",
          "align": "high"
        },
        "labels": {
          "overflow": "justify"
        }
      },
      "tooltip": {
        "valueSuffix": " millions"
      },
      "plotOptions": {
        "bar": {
          "dataLabels": {
            "enabled": true
          }
        }
      },
      "exporting": {
        "chartOptions": {
          "chart": {
            "events": {
              "load": {}
            }
          },
          "style": {
            "fontFamily": "Arial"
          }
        }
      },
      "legend": {
        "enabled": false
      },
      "credits": {
        "enabled": false
      },
      "series": [
        {
          "name": "Year 1800",
          "data": [
            107,
            31,
            635,
            203,
            2
          ]
        },
        {
          "name": "Year 1900",
          "data": [
            133,
            156,
            947,
            408,
            6
          ]
        },
        {
          "name": "Year 2008",
          "data": [
            973,
            914,
            4054,
            732,
            34
          ]
        }
      ]
    }
  }
}
```

**Comment by Daemach** [comment]
Just following up, I created a second function with the base code and it
does indeed function with 640MB of RAM as described.  I cannot get the
API-based version of your code to run with less than 4096.  There really
should be no difference between the two, but there it is.

**Comment by tarkal** [comment]
By `API-based version` do you mean **API Gateway**?

**Comment by Daemach** [comment]
Yes, I believe so.  When I use this zip file to create a function it will not run in a reasonable time frame without 4GB of RAM: https://github.com/tarkal/highchart-lambda-export-server/blob/master/dist/highcharts-export-server%20Lambda-API-Gateway.zip  For example, I lowered it to 3000MB and it takes 5 seconds on average.  At 2GB of RAM, it times out after 10 seconds (my current threshold).  If I kick it up to max, it runs in about 1.5 seconds.

When I use your other zip file, it runs with 640MB like you said earlier.  I don't know what the difference would be.

**Comment by tarkal** [comment]
That package was assembled by a contributor @fcwheeler. I never tested that package directly so I don't know what modifications he made or how he compiled it. A couple of options for you; 
1. Contact @fcwheeler and ask them about how they compiled their version
2. Just use my package and create a proxy Lambda function that receives the API gateway request and calls the HighChart function.
3. Follow my instructions to compile your own version and see if you get the same performance as my original version. If you do then you can just modify the `index.js` file so that it extracts the chart settings from the API gateway request.

**Comment by Daemach** [comment]
Gotcha.  Thank you.

I updated your original package so that it would work for the API or as you
had it originally.  With 1769mb of RAM it executes in about 600ms.
https://www.dropbox.com/t/v1ho7A9F48zhzkVC

I think the speed/memory issue with the other zip was that he was launching
50 phantomjs workers instead of 2.  Thanks again for your work on this!
