### ISSUE TITLE
How to select HighStock chart type

### ISSUE THREAD

**Issue by gustavocampos** [tarkal/highchart-lambda-export-server#2]
I'm using the old Java Highchart export server currently, looking forward to change to this one, but I couldn't find how to send a parameter choosing between Highcharts and Highstock, is there a way to do that?

Also, how do I know which Highcharts version (i.e. v8.0.4) is being used by this exporter?

Thank you very much!

**Comment by tarkal** [comment]
We actually don't use _Highstock_ so I can't say for sure. However, as best as I remember you would need to follow the [instructions](https://github.com/tarkal/highchart-lambda-export-server/blob/master/README.md) and build the export server yourself. When you come to install _Highcharts_ it will ask you if you want to include _Highstock_ . 

The same would go for the version. You will need to build it yourself as the latest version will be installed by default. You can then verify the version yourself.

Hope that helps.
